### ISSUE TITLE
Bug report: running exp_sarsa_1

### ISSUE THREAD

**Issue by raharth** [raharth/PyTorch_Lib#55]
epoch: 45	average reward: -0.87	latest average reward: -1.10
Evaluation environment...
Evaluation reward for sarsa: -1.90
100%|██████████| 10/10 [00:00<00:00, 434.39it/s]
78it [00:00, 87.76it/s]
Traceback (most recent call last):
  File "D:/projects/PyMatch/research_master/train_learner.py", line 25, in <module>
    learner.fit(**params['fit'])
  File "D:\projects\PyMatch\pymatch\DeepLearning\learner.py", line 184, in fit
    train_loss = self.fit_epoch(device)
  File "D:\projects\PyMatch\pymatch\ReinforcementLearning\learner.py", line 520, in fit_epoch
    target[mask] = (1 - self.alpha) * target[mask] + self.alpha * (
IndexError: The shape of the mask [64, 1] at index 1 does not match the shape of the indexed tensor [64, 2] at index 1

**Comment by raharth** [comment]
This seems to be random... sometimes it happens sometimes it doesnt....

**Comment by raharth** [comment]
Simply happens due to the one_hot_encoding which is buggy
